nofrixion/nofrixion.business

- bff/NoFrixion.Bff.sln
- bff/NoFrixion.Bff/ConfigKeys.cs
- bff/NoFrixion.Bff/Nofrixion.Bff.csproj
- bff/NoFrixion.Bff/Pages/Index.cshtml
- bff/NoFrixion.Bff/Pages/Index.cshtml.cs
- bff/NoFrixion.Bff/Program.cs
- bff/NoFrixion.Bff/appsettings.json
- Removed ref to Nofrixion.Common
- 
- Added ConfigKeys
- 
- Modified routing
> Created Index razor page to serve js from appSettings

- apps/business/src/App.tsx
- bff/NoFrixion.Bff/Program.cs
If an old route without '/home' is entered, try to redirect to correct route.
> If an old route without '/home' is entered, try to redirect to correct route

- packages/components/src/components/ui/Account/AccountBalance/AccountBalance .stories.tsx
- packages/components/src/components/ui/Account/AccountBalance/AccountBalance.stories.tsx
- packages/components/src/components/ui/Account/AccountBalance/AccountBalance.tsx
- packages/components/src/components/ui/Account/AccountCard.tsx
Re-usable Account balance component
> Moov 2129 Account balance component 

- packages/components/src/components/ui/Account/AccountBalance/AccountBalance.tsx
> Account balance 2rem/32px

- aws-pipelines/aws-dev-pr-business-js-build-push.yml
To ease deletion of ephemeral JS artifacts, a pair of index tags were added to the Azure Blobs to identify them.
> Added index tags to PR pipeilne JS file blobs

- packages/components/src/assets/icons/bitcoin-icon-unavailable.svg
- packages/components/src/components/ui/Modals/PaymentMethodsModal/PaymentMethodsModal.tsx
Temporarily disabled the Bitcoin Lightning payment method when creating payment requests.
> [MOOV-2081]: Disabled Bitcion Lightning payment method

- apps/business/src/index.css
- packages/components/src/index.css
By using this Inter font, I can't notice a difference in the font weights between Figma and MM4B
**MM4B**
**Figma**
> Changed font to fix font feature settings and weights

- apps/business/src/index.css
- apps/business/src/pages/layout.tsx
- apps/business/src/root.tsx
- package-lock.json
- package.json
> Added font smoothing to entire app

- packages/web-components/src/CurrentAccountsList.tsx
- packages/web-components/src/index.ts
This pull request introduces the `current-accounts-list` web component.
Key Notes:
- 🔥 This is the first component to receive a function.
- ✅ It has been tested locally, integrated into the Portal, and is functioning as expected.
- 🚀 Following this PR, another will be opened in the MoneyMoov Portal (API solution) to display the new Current Accounts List.
- 🔜 This implementation includes only the list functionality; account details will be addressed in a future update.
> Implement "current-accounts-list" Web Component

- package-lock.json
- packages/components/package.json
- packages/components/src/components/ui/BankRefundModal/BankRefundModal.tsx
- packages/components/src/components/ui/CaptureModal/CaptureModal.tsx
- packages/components/src/components/ui/CardRefundModal/CardRefundModal.tsx
- packages/components/src/components/ui/CreatePaymentRequestPage/CreatePaymentRequestPage.tsx
- packages/components/src/components/ui/InputAmountField/InputAmountField.tsx
- packages/web-components/package.json
This pull request refines the way we handle decimals in the `InputAmountField` component. Specifically, these changes target the amount fields within the "Create Payment Request" and "Refund" sections. The enhancements bring greater consistency and usability to the input mechanism for decimals.
> Enhance Decimal Handling in InputAmountField Component

- apps/business/src/components/HotjarInjection.tsx
- aws-pipelines/aws-prod-business-js-build-push.yaml
- aws-pipelines/aws-sandbox-business-js-build-push.yaml
This pull request addresses an issue where the production environment was using the Hotjar tag intended for development. The correct tag for production has been implemented, and a new Hotjar tag for the Sandbox environment has also been added (as discussed with Andrés).
Notes:
- I'm seeking @agranillonf review on this. I'd like to confirm if the changes made are the sole steps required for adding the environment variable. It appears to be correct, but a double-check would be appreciated.
> Update Hotjar Tags Across Environments

- packages/components/src/components/ui/CreatePayoutModal/CreatePayoutModal.tsx
- packages/components/src/components/ui/InputAmountField/InputAmountField.tsx
Fixed validation issue with IBAN and other fields.
The problem was that the validations for text fields were setting the validation message on change but the button click was not validating some of the fields.
Added all validation checks on button click instead of relying on messages.
Found another issue when merchant is switched and create payout button breaks. Fixed it.
> Fixed validation issue with IBAN

- packages/components/src/components/ui/Account/AccountCard.stories.tsx
- packages/components/src/components/ui/InputAmountField/InputAmountField.stories.tsx
- packages/components/src/components/ui/molecules/Select/SelectSorter/SelectSorter.stories.tsx
- packages/components/src/utils/mockedData.ts
This pull request addresses an issue with the Storybook build, which is utilised by Chromatic.
> Fix Storybook Build for Chromatic Integration

- packages/components/src/components/ui/Loader/Loader.tsx
- packages/components/src/components/ui/organisms/TransactionsTable/TransactionsTable.tsx
- packages/components/src/utils/parsers.ts
This addresses bugs [MOOV-2273] and [MOOV-2272]
1. Use your reference for payins
2. Fixed time format issue
[MOOV-2273]: https://nofrixion.atlassian.net/browse/MOOV-2273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOOV-2272]: https://nofrixion.atlassian.net/browse/MOOV-2272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Use your ref for payins

- packages/components/src/components/ui/organisms/PayoutsTable/PayoutsTable.tsx
Improved clickability of payout checkboxes
> Improved clickability of payout checkboxes

- packages/components/src/components/functional/PayoutDashboard/PayoutDashboard.tsx
Filtering beneficiaries by merchant ID
> Filter beneficiaries by merchant

- packages/components/src/components/ui/atoms/Select/Select.tsx
Added max-height to the "From account" dropdown list of the Create Payout page to make it scrollable when needed.
> [MOOV-2283]: Added max height to payout account select control

- packages/components/src/components/ui/Tab/Tab.tsx
Reduced padding and font-size on smaller resolutions to accommodate for long Tab titles, like "Pending approval".
> [MOOV-2299]: Fixed "Pending approval" size on smaller screens

- packages/components/src/components/functional/PayoutDashboard/PayoutDashboard.tsx
- packages/components/src/components/ui/organisms/PayoutsTable/PayoutsTable.tsx
- packages/components/src/components/ui/pages/PayoutDashboard/PayoutDashboard.tsx
Updated the Payout dashboard to show loader as per new approach taken for PR dashboard.
> Payout dashboard loading style updated to look like PR dashboard

- packages/components/src/components/ui/CreatePaymentRequestPage/CreatePaymentRequestPage.tsx
Update user defaults if they select the checkbox. 
Never remove user defaults
> Only update user defaults if they select the defaults checkbox.

- packages/components/src/components/ui/PaymentRequestRow/PaymentRequestRow.tsx
Fixed merge issue where column got duplicated.
> Fixed merge issue

- packages/components/src/components/ui/PaymentRequestRow/PaymentRequestRow.tsx
- packages/components/src/components/ui/PaymentRequestTable/PaymentRequestTable.tsx
Renamed amount to requested and changed currency to symbol.
> Renamed amount to requested

- apps/business/src/components/HotjarInjection.tsx
This pull request corrects an inconsistency in the Hotjar tags setup. Previously, Hotjar tags were mismatched across environments. With this update, each environment (dev, sandbox, & prod) will now have the appropriate Hotjar tag.
> Fix Hotjar Tags for Each Environment

- packages/components/src/components/ui/CreatePaymentRequestPage/CreatePaymentRequestPage.tsx
Now accepting any chars that can get past the xss check.
> Remove payment request description regex validation. 

- packages/clients/src/hooks/usePaymentRequest.ts
- packages/clients/src/hooks/usePaymentRequests.ts
- packages/clients/src/types/Enums.ts
- packages/clients/src/types/props.ts
- packages/components/src/components/functional/PaymentRequestDashboard/PaymentRequestDashboard.tsx
- packages/components/src/components/functional/PaymentRequestDetailsModal/PaymentRequestDetailsModal.tsx
- packages/components/src/components/ui/PaymentRequestRow/PaymentRequestRow.tsx
- packages/components/src/components/ui/PaymentRequestTable/PaymentRequestTable.tsx
- packages/components/src/components/ui/TransactionsTooltip/TransactionsTooltip.stories.tsx
- packages/components/src/components/ui/TransactionsTooltip/TransactionsTooltip.tsx
- packages/components/src/components/ui/atoms/Icon/Icon.tsx
- packages/components/src/components/ui/molecules/Status/Status.tsx
- packages/components/src/types/LocalTypes.ts
- packages/components/src/utils/parsers.ts
- packages/components/src/utils/paymentAttemptsHelper.ts
Added paid column to payment requests table.
> Added paid column

- packages/components/src/components/ui/FilterButton/FilterButton.tsx
Set the minimum width of filter content to 320px (20rem) and the maximum width to 640px (40rem).
> Set filter content width limits

- packages/components/src/components/functional/CurrentAccountsList/CurrentAccountsList.tsx
- packages/components/src/components/ui/Modals/ConnectBankModal/ConnectBankModal.tsx
- packages/components/src/utils/utils.ts
> Added business banks to banks list

- bff/NoFrixion.Bff/Controllers/ApproveController.cs
> Added beneficiary auth to bff

- apps/business/src/lib/auth/RoleProtectedRoute.tsx
- apps/business/src/pages/NewlyRegistered.tsx
- packages/components/src/components/ui/atoms/Icon/Icon.tsx
> Newly registered page

- packages/components/src/components/ui/atoms/Card/Card.tsx
- packages/components/src/components/ui/molecules/MostActiveAccountRow/MostActiveAccountRow.tsx
This pull request enhances the responsiveness of the accounts widget card on mobile devices.
Changes made include adjustments to the layout and spacing to ensure that the accounts widget card displays optimally on mobile screens. These enhancements are based on the provided design.
> Improve Responsiveness of Mobile Accounts Widget Card

- packages/components/src/components/ui/DashboardTab/DashboardTab.tsx
- packages/components/src/components/ui/PaymentRequestStatusBadge/PaymentRequestStatusBadge.tsx
- packages/components/src/components/ui/molecules/Status/Status.tsx
- packages/components/src/types/LocalTypes.ts
- packages/components/src/utils/parsers.ts
Renamed authorized to authorised.
> Renamed authorized to authorised.

- packages/components/src/components/ui/PaymentRequestRow/PaymentRequestRow.stories.tsx
- packages/components/src/components/ui/PaymentRequestRow/PaymentRequestRow.tsx
- packages/components/src/types/LocalTypes.ts
- packages/components/src/utils/mockedData.ts
- packages/components/src/utils/parsers.ts
1. Handle null exception for payment events
2. Fixed mocked data's missing fields
> Handle null exception for payment events

- apps/business/src/pages/accounts-receivable/page.tsx
- apps/business/src/pages/payouts/page.tsx
- apps/business/src/pages/users/page.tsx
- packages/components/src/components/functional/PaymentRequestDashboard/PaymentRequestDashboard.tsx
- packages/components/src/components/functional/PayoutDashboard/PayoutDashboard.tsx
- packages/components/src/components/functional/UserDashboard/UserDashboard.tsx
https://github.com/nofrixion/nofrixion.business/assets/92720032/2a7fe10a-6f91-49b9-a71d-ae5edf44160f
> On un-authorised don’t log user out, show error

- packages/components/src/components/ui/BankRefundModal/BankRefundModal.tsx
> Disable bank refund button when not available

- packages/components/src/components/ui/CreatePaymentRequestPage/CreatePaymentRequestPage.tsx
- packages/components/src/components/ui/InviteUserModal/InviteUserModal.tsx
- packages/components/src/components/ui/Modals/PaymentNotificationsModal/PaymentNotificationsModal.tsx
- packages/components/src/utils/validation.ts
Max length 254 char
Don't allow space in email
Minimum format: a@b.co
> Fix email validation

- package-lock.json
- packages/clients/src/types/ApiResponses.ts
- packages/components/src/components/ui/DetailsTabs/DetailsTabs.tsx
- packages/components/src/types/LocalTypes.ts
- packages/components/src/utils/mockedData.ts
- packages/components/src/utils/parsers.ts
- packages/components/src/utils/paymentAttemptsHelper.ts
> Record bank authorisation failure

- packages/components/src/components/ui/organisms/SavePayoutModal/SavePayoutModal.tsx
Refer https://nofrixion.atlassian.net/browse/MOOV-2700 to understand use case.
> Button text change for non-authorisers.
