nofrixion/nofrixion.business

- apps/business/src/components/HomeUI.tsx
Fixed an issue where the home UI would flash when focusing back on the browser. Implemented the `finishedFirstLoading` state to prevent the page from flashing the loader as `react-query` fetches user data upon page focus.
This change enhances the user experience by providing a smoother interface when interacting with the app, especially during task-switching or tab-switching in the browser.
> Fix Flashing Home UI on Browser Focus

- packages/components/src/components/ui/CreatePaymentRequestPage/CreatePaymentRequestPage.tsx
This pull request addresses a warning that was appearing in the console related to having multiple child components with the same key in the Payment Requests view. The issue has been resolved by ensuring unique keys for each child component. An image highlighting the original warning is attached to this PR for clarity.
> Fix Duplicate Key Warning in Payment Requests View

- package-lock.json
- packages/components/package.json
- packages/components/src/components/ui/CaptureModal/CaptureModal.tsx
- packages/components/src/components/ui/CreatePaymentRequestPage/CreatePaymentRequestPage.tsx
This pull request addresses the following:
1. **App Unusability Post PR Creation**: There was a persisting issue where the app became unusable after creating a Payment Request and subsequently closing the details modal. This was due to the `@headlessui/react` library applying an `overflow: hidden` style directly to the HTML page without removing it afterward. To resolve this, the `@headlessui/react` was updated to its latest version. After this update, upon creating a total of 50 Payment Requests (28 on Chrome and 22 on Safari), the issue did not recur.
2. **CSS Class Correction**: Three instances were identified where CSS class names needed to be updated,`bg-greyText` was updated to `bg-grey-text`.
> Fix App Unusability Issue Post PR Creation and Correct CSS Class Naming

- packages/components/src/components/ui/CreatePaymentRequestPage/CreatePaymentRequestPage.tsx
- packages/components/src/components/ui/CustomModal/CustomModal.stories.tsx
- packages/components/src/components/ui/CustomModal/CustomModal.tsx
- packages/components/src/components/ui/Modals/PaymentConditionsModal/PaymentConditionsModal.tsx
- packages/components/src/components/ui/Modals/PaymentMethodsModal/PaymentMethodsModal.tsx
- packages/components/src/components/ui/Modals/PaymentNotificationsModal/PaymentNotificationsModal.tsx
As discussed, the payment method defaults checkbox will always be shown to the user.
Also, fixed an issue with the gray background of the Create Payment Request button's disabled state.
> [MOOV-2125]: Reverted dynamic payment method defaults checkbox display logic

- apps/business/src/App.tsx
- apps/business/src/components/AccountPayableCard.tsx
- apps/business/src/components/AcountsReceivableCard.tsx
- apps/business/src/components/ui/atoms/Card/Card.tsx
- apps/business/src/components/ui/molecules/AccountsCarousel.tsx
- apps/business/src/pages/current-accounts/[id].tsx
- apps/business/src/pages/current-accounts/account-dashboard.tsx
- apps/business/src/pages/current-accounts/page.tsx
- packages/clients/src/clients/AccountsClient.ts
- packages/clients/src/hooks/index.ts
- packages/clients/src/hooks/useAccount.ts
- packages/components/src/components/functional/AccountDashboard/AccountDashboard.stories.tsx
- packages/components/src/components/functional/AccountDashboard/AccountDashboard.tsx
- packages/components/src/components/functional/CurrentAccountsList/CurrentAccountsList.stories.tsx
- packages/components/src/components/functional/CurrentAccountsList/CurrentAccountsList.tsx
- packages/components/src/components/ui/Account/AccountCard.tsx
- packages/components/src/components/ui/Account/CurrentAccountsHeader/CurrentAccountsHeader .tsx
- packages/components/src/components/ui/Account/CurrentAccountsList/CurrentAcountsList.tsx
- packages/components/src/components/ui/atoms/Button/Button.tsx
- packages/components/src/components/ui/atoms/DisplayAndCopy/DisplayAndCopy.tsx
- packages/components/src/components/ui/atoms/Icon/Icon.tsx
- packages/components/src/components/ui/organisms/TransactionsTable/TransactionsTable.tsx
- packages/components/src/components/ui/pages/AccountDashboard/AccountDashboard.stories.tsx
- packages/components/src/components/ui/pages/AccountDashboard/AccountDashboard.tsx
- packages/components/src/index.ts
- packages/components/src/utils/mockedData.ts
This pull request encompasses several updates related to the AccountDashboard:
- Introduced the `AccountDashboard` UI component.
- Developed the `AccountDashboard` functional component.
- Integrated the `AccountDashboard` functional component into the existing Current Accounts page in Business. With this update, users can click on any account from the Current Account Lists to dive deeper into its balance details and view all associated transactions.
Please be aware of the following considerations:
1. Pablo I. has not been included in this review. The intent is to have this primarily as a dev review. Post-merging this PR, I'll be talking with Pablo I. for a review in Business Dev, ensuring he can access it without any additional setup.
2. There are some missing UI details, such as skeleton …
> Integrate `AccountDashboard` Component into Current Accounts Page

- apps/business/src/lib/auth/userAuth.tsx
Modifications made:
- Initially, adjustments were made to utilise the `/pr/{number}` URL structure over the direct `/{prNumber}` format. However, after observing that #35 already addressed the issues those changes aimed to solve, those modifications were reverted.
- Enhanced the logout functionality: Now, when a user logs out, the system redirects back to the URL containing the PR number. This ensures that users are consistently brought back to the version of the Portal associated with the Pull Request.
> Eenhance PRs logout behavior

- apps/business/src/components/ui/ScrollArea.tsx
- apps/business/src/components/ui/molecules/AccountsCarousel.tsx
- apps/business/src/pages/dashboard/page.tsx
In this pull request:
1. Fixed an issue where the arrows used to scroll through the current account cards weren't visible on initial load. With this fix, arrows will always be displayed if there's a card to be shown, whether on the left or right side of the screen.
2. Updated the card designs to align more closely with the specified design. This includes adding a gradient to the edges near the arrows.
**Important Note**: Due to some limitations, introducing the gradient arrows required a trade-off. The snapping feature on the cards has been removed. Now, clicking on the arrow will scroll a fixed amount of content instead of snapping the card to the beginning. If we kept the snapping feature, cards would align directly to the screen's edge without any padding.
> Fix Account Card Arrows (in carousel)

- packages/components/src/components/ui/Transactions/Transactions.tsx
- packages/components/src/utils/parsers.ts
The payment attempts are now order by descending order so latest first. 
Fix for #MOOV-2161 and #MOOV-2162
> Sort payment attempts

- packages/web-components/src/AccountDashboard.tsx
- packages/web-components/src/AccountsReceivableDashboard.tsx
- packages/web-components/src/CurrentAccountsList.tsx
- packages/web-components/src/index.ts
This pull request includes the addition of the `account-dashboard` web component.
Notes:
- The component has been tested locally by incorporating it into the Portal, and it appears to work as expected.
- A follow-up PR will be created on the MoneyMoov Portal (API solution) to display the new Accounts Dashboard.
> Add account-dashboard Web Component

- packages/components/src/components/ui/CustomModal/CustomModal.tsx
This pull request addresses the issue where, after setting a Payment Request (PR) configuration, the modal would close, causing the page to scroll back to the top. With these changes, the page will remain in its current position after the modal closes.
Important notes:
- Adjustments were made to the chore of the modal. It's essential to thoroughly review all three PR configuration modals to ensure they function correctly. This includes checking the animations to ensure smooth transitions.
> Fix Scroll Reset Issue on Payment Request Configuration Modal Close

- packages/components/src/components/ui/QRCode/QRCode.tsx
- packages/components/src/components/ui/atoms/Icon/Icon.tsx
In this update, the mobile experience for viewing the QR code in the Payment Request Details has been enhanced:
1. Instead of downloading a QR code, users will now see a modal that directly displays the QR Code when they click on the icon button. This provides a more seamless and intuitive experience, eliminating the need to download and open a separate image.
2. The icon button's design has been modified to better represent its new functionality of displaying the QR code rather than downloading it.
Notes:
- Please note that this hasn't been tested on a real device yet due to deployment requirements. It's recommended to test this feature on a physical device once it's deployed.
Demo video:
https://github.com/nofrixion/nofrixion.business/assets/52673485/c05facd8-a29b-4136-b432-3e974b51bf3b
> Improved QR Code Display in Payment Request Details on mobile

- packages/components/src/components/functional/PayoutDashboard/PayoutDashboard.tsx
- packages/components/src/components/ui/CreatePayoutModal/CreatePayoutModal.tsx
The issue was happening because of a change I made to fix the issue with changing merchant. The issue was easily fixed by reverting the change but the merchant change issue remained.
The create payout modal became unstable on changing the merchant. After a lot of trying I figured out the core issue. It was happening because the useAccounts takes some time to refresh the accounts and the modal uses the last merchants accounts till then and goes into an unstable state because the accounts dropdown looks for the id of the previously selected account.
Now I am showing the modal only when the accounts have refreshed.
Also fixed a few othe rissues.
> Create payout modal issue

- packages/clients/src/hooks/useAccount.ts
- packages/components/src/components/functional/AccountDashboard/AccountDashboard.tsx
- packages/components/src/components/functional/CurrentAccountsList/CurrentAccountsList.tsx
- packages/components/src/components/functional/PaymentRequestDashboard/PaymentRequestDashboard.tsx
- packages/components/src/components/functional/PayoutDashboard/PayoutDashboard.tsx
- packages/components/src/components/ui/PaymentRequestTable/PaymentRequestTable.tsx
- packages/components/src/components/ui/organisms/TransactionsTable/TransactionsTable.tsx
- packages/components/src/components/ui/pages/AccountDashboard/AccountDashboard.tsx
Added skeleton to transactions table to show loading effect.
While testing, realized that the account name takes some time to load on account dashboard. Added placeholder data for account as we have the account information already in cache.
Changed new QueryClient() to useQueryClient in some places. Using new QueryClient() creates a new instance and can't find the queries in the query cache.
Fixed some minor issues in loading of Payment requests dashboard.
> Added skeleton to transactions.

- apps/business/src/components/Navbar/Navbar.tsx
- apps/business/src/components/Navbar/NavbarItem.tsx
- apps/business/src/components/Navbar/UserNav.tsx
- apps/business/src/lib/constants.ts
When on 1280px or higher width viewports, the original horizontal nav menu will be displayed.
Note: It'll be worth to test with long merchant names.
> [MOOV-2084]: Restored dynamic horizontal navigation menu

- packages/components/src/components/ui/organisms/TransactionsTable/TransactionsTable.tsx
- packages/components/src/components/ui/pages/AccountDashboard/AccountDashboard.tsx
In this update, the "Type" column indicating the network has been removed exclusively for connected accounts, given the unavailability of that information. It's important to note that the "Type" column will still be displayed for regular (non-connected) accounts.
Here's a visual comparison of the changes made for a connected account:
| Before | After |
|--------|--------|
| <img width="1624" alt="Before" src="https://github.com/nofrixion/nofrixion.business/assets/52673485/f2b8d939-2aff-4dbd-843d-c9660f546f00"> | <img width="1624" alt="After" src="https://github.com/nofrixion/nofrixion.business/assets/52673485/c14194d0-c3fd-4844-8f2c-918ad5dd2f20"> |
> Remove "Type" Column for Connected Accounts

- packages/components/src/components/ui/Contact/Contact.tsx
- packages/components/src/components/ui/PaymentRequestDetails/PaymentRequestDetails.tsx
- packages/components/src/components/ui/QRCode/QRCode.tsx
This pull request addresses a UI issue in the Payment Request Details modal. Previously, long customer names or emails would cause the QR code to be compressed, rendering it nearly illegible. With this fix, long customer names and emails are now displayed appropriately without affecting the QR code's size or readability.
> Fix Display Issue for Long Customer Names/Emails in Payment Request Details Modal

- package-lock.json
- packages/components/package.json
- packages/components/src/components/ui/molecules/Chart/AccountChart.stories.tsx
- packages/components/src/components/ui/molecules/Chart/AccountChart.tsx
This pull request introduces a new component - the Account Graphic (Chart)UI.
You can test this component in Storybook under "[Molecules/Account Chart](https://64d9fa344203198b9ba80047-rwzqtffbab.chromatic.com/?path=/story/molecules-account-chart--default)" Additionally, you have the flexibility to manipulate the chart's data by adjusting the `points` and `currency` props.
Demo video showing how to do so:
https://github.com/nofrixion/nofrixion.business/assets/52673485/48912fc1-7b51-4b55-9c36-afe1ef9e86a2
> Add Account Graphic (Chart) UI

- packages/components/src/components/ui/PaymentRequestTable/PaymentRequestTable.tsx
- packages/components/src/types/LocalTypes.ts
- packages/components/src/utils/parsers.ts
Updated the Delete Payment Request button logic to enable deletion of payment requests with events and status 'None', which will archive the record rather than delete it.
**Note:** Depends on MoneyMoovAPI PR #1322 to work.
> [MOOV-2305]: Added possibility to archive payment requests

- packages/components/src/components/functional/AccountDashboard/AccountDashboard.tsx
- packages/components/src/components/functional/CurrentAccountsList/CurrentAccountsList.tsx
- packages/components/src/components/functional/PaymentRequestDashboard/PaymentRequestDashboard.tsx
- packages/components/src/components/ui/Account/CurrentAccountsList/CurrentAcountsList.tsx
- packages/web-components/src/AccountDashboard.tsx
- packages/web-components/src/AccountsReceivableDashboard.tsx
- packages/web-components/src/CurrentAccountsList.tsx
This commit addresses two issues related to the account list and web components in general:
1. The build was failing for all components due to the absence of the `QueryClient`, which had been accidentally deleted in a previous [commit](https://github.com/nofrixion/nofrixion.business/commit/e05b3555c25f1e7fa38a49bc08cf8cf30445b072). To resolve this, a new `QueryClient` is now created when building web components. For non-web components, the `useQueryClient()` hook is used to retrieve it.
2. The CurrentAccountList (`current-accounts-list`) component was not functioning correctly because it relied on `useNavigate`, which was primarily used for handling connected accounts. It was decided to remove Connected Accounts support for web components due to its complexity. To adapt the component, a …
> Ensure build compatibility for account list and transactions (web-components)

- packages/components/src/components/functional/AccountDashboard/AccountDashboard.tsx
- packages/components/src/components/ui/pages/AccountDashboard/AccountDashboard.tsx
This PR introduces a skeleton loading feature to the Current Account page, specifically targeting the display of account name, identifier, and balance.
- **Skeleton Loading for Account Details**: Implemented skeleton loaders for the account name, identifier, and balance sections. This provides a smoother user experience during data loading phases, replacing blank spaces with visually appealing placeholders.
Demo video:
https://github.com/nofrixion/nofrixion.business/assets/52673485/5a406ba4-663d-410e-92ee-eafa14cc49ae
> Implement Skeleton Loading for Account Details on Current Account Page

- packages/clients/src/clients/BaseApiClient.ts
- packages/clients/src/clients/PayoutClient.ts
1. Adds the ability to attach an `idempotency-key` header to a POST request.
2. Enabled for the `PayoutClient`
> Idempotent header

- packages/components/src/components/ui/Tags/AddTag/AddTag.tsx
Previously, users could add the same tag multiple times to a single Payment Request. This update prevents the addition of duplicate tags to a Payment Request.
- **Duplicate Tag Prevention**: Implemented a check to disallow adding a tag to a Payment Request if it already exists.
> Prevent Duplicate Tags in Payment Requests

- packages/components/src/components/ui/Account/CurrentAccountsList/CurrentAcountsList.tsx
- packages/components/src/components/ui/Account/External/ExternalAccountConnectCard.tsx
Changes suggested by Pablo I when there are no payment accounts are:
1. To not show the Current Accounts title and just show the connected accounts card in case there are no payment accounts. The reasoning is that the customer having no payment accounts would obviously be using AIS services and would know that this is expected.
2. To hide the "Maybe later" link on the card as this is the only option such a customer would have.
This is hard to test for Pablo I so attaching a video.
https://github.com/nofrixion/nofrixion.business/assets/103389834/e3ce062a-6e5d-4d78-94b2-a342774e3c2c
> UI changes for no payment accounts.

- packages/components/src/components/functional/CreatePaymentRequestPage/CreatePaymentRequestPage.tsx
- packages/components/src/components/ui/CreatePaymentRequestPage/CreatePaymentRequestPage.tsx
- packages/components/src/components/ui/CustomModal/CustomModal.tsx
- packages/components/src/components/ui/EditOptionCard/EditOptionCard.tsx
- packages/components/src/components/ui/Modals/PaymentMethodsModal/PaymentMethodsModal.tsx
- packages/components/src/components/ui/Select/Select.tsx
- packages/components/src/types/LocalTypes.ts
This PR introduces the ability to select a destination account for the Pay by Bank feature in the Create Payment Request modal, reinstating a functionality that was present in the old portal. This enhancement is crucial for customers with multiple NoFrixion accounts, allowing them to specify the account where the funds should be received.
- **Destination Account Picker**: Added a picker in the Create Payment Request modal for selecting the destination account. This feature aligns with the currency selected for the Payment Request.
- **Currency-Matched Accounts**: The accounts displayed in the picker correspond to the currency of the Payment Request. If there's only one account for the selected currency, only that account is shown.
- **Behaviour on Currency Change**: If the currency is …
> Implement Destination Account Selection in Create Payment Request Modal

- packages/components/src/components/ui/CreatePaymentRequestPage/CreatePaymentRequestPage.tsx
- packages/components/src/components/ui/Modals/PaymentMethodsModal/PaymentMethodsModal.tsx
- **Spelling Standardisation**: Replaced instances of “Authorize” with “Authorise” across the application.
> Standardise Spelling to 'Authorise'

- packages/components/src/components/functional/PaymentRequestDashboard/PaymentRequestDashboard.tsx
- packages/components/src/components/ui/PaymentRequestTable/PaymentRequestTable.tsx
- Accounts receivable dashboard loader will not wait for the payment request fetch API call if the metrics result is empty (0 on all statuses).
- Fixed initial and subsequent 'empty' states.
> [MOOV-2631,MOOV-2635]: Small bugfixes to PR Dashboard empty state

- packages/components/src/components/ui/Checkbox/Checkbox.tsx
Forced `whitespace-nowrap` on the `Checkbox` element when no `description` property is provided to avoid having short labels break.
> [MOOV-2683]: Disabled word break on the EditColumns menu

- packages/components/src/components/ui/TableScrollbar/TableScrollbar.tsx
- packages/components/src/components/ui/organisms/SavePayoutModal/SavePayoutModal.tsx
When creating a new payout, an authoriser should see "Create and authorise payout" while when editing, they should see, "Save and authorise payout".
Made a minor change to use predefined class name for duration of 100ms in table scrollbar.
> Button text change when creating new payout 

- packages/components/src/components/ui/For/For.stories.tsx
- packages/components/src/components/ui/For/For.tsx
- packages/components/src/components/ui/PaymentRequestRow/PaymentRequestRow.tsx
Found an issue with Contact component which is primarily for the payment request details modal which displays the name and email of customer. This component was reused for the FOR column but it's actually different from contact. Created a separate component which covers all cases when some or the other data won't be available.
Check the storybook to go through all the cases.
> New component for FOR column in payment request table.

- packages/components/src/utils/validation.ts
Modified the email regular expression to allow plus signs before the '@' character, just like in the API.
> [MOOV-2673]: Added plus sign to email regex

- packages/components/src/components/ui/molecules/AnimatedTabs/AnimatedTabs.tsx
On mobile, the green tab accents would overlap with any visible pop-over or drop-down element.
> [MOOV-2705]: Fixed tab decorations overlapping with menus
